/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.models.online.system.kafka.download.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum DownloadApprovalStatus implements org.apache.avro.generic.GenericEnumSymbol<DownloadApprovalStatus> {
  APPROVED, REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DownloadApprovalStatus\",\"namespace\":\"com.models.online.system.kafka.download.avro.model\",\"symbols\":[\"APPROVED\",\"REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
